// src/utils/audioMap.js
// AUTO-GENERATED by scripts/generate_audio.js — do not edit by hand.
// Run `npm run generate-audio` to regenerate.

export const audioMap = {
  "Hmm, I wonder! Sophie is holding a bag of apples that feels very heavy. But how do we know exactly how heavy it is? Think about the tools we use to measure things — then click Let's Discover!": "assets/audio/audio_hmm_i_wonder_sophie_is_holding_a_bag_of_apples_that_fee_0.mp3",
  "Ooh, a mass mystery! Lily's recipe needs 500 grams of flour. Is that more or less than one kilogram? Think carefully — then let's find out together!": "assets/audio/audio_ooh_a_mass_mystery_lilys_recipe_needs_500_grams_of_flou_1.mp3",
  "Great thinking challenge! A watermelon weighs 3 kilograms and a mango weighs 400 grams. Which one is heavier? Can you figure it out before we start?": "assets/audio/audio_great_thinking_challenge_a_watermelon_weighs_3_kilogram_2.mp3",
  "What a tricky one! Oliver has two boxes with different masses. Can you work out which box is heavier — and by how much? Think it through, then let's discover!": "assets/audio/audio_what_a_tricky_one_oliver_has_two_boxes_with_different_m_3.mp3",
  "Welcome to Market Day! Sophie and Max visit the market where Max uses a balance scale to weigh strawberries. A balance scale compares masses — the heavier side always goes down!": "assets/audio/audio_welcome_to_market_day_sophie_and_max_visit_the_market_w_4.mp3",
  "When we weigh small things like sweets, spices, or a pencil, we use grams! The letter g stands for grams. Small objects have a small mass — so we measure them in grams!": "assets/audio/audio_when_we_weigh_small_things_like_sweets_spices_or_a_penc_5.mp3",
  "When things are heavier — like bags of flour or boxes of fruit — we use kilograms! The letters k g stand for kilograms. One kilogram is much heavier than one gram!": "assets/audio/audio_when_things_are_heavier_like_bags_of_flour_or_boxes_of__6.mp3",
  "Here is the most important fact to remember: one kilogram equals one thousand grams! So 1 kg equals 1000 g. And 500 grams is half a kilogram. Write this down — it is your superpower!": "assets/audio/audio_here_is_the_most_important_fact_to_remember_one_kilogra_7.mp3",
  "Amazing work! You have learned four powerful ideas. We compare masses using a balance scale. Small things are measured in grams. Heavy things are measured in kilograms. And one kilogram equals one thousand grams. You are a Mass Master — let's play!": "assets/audio/audio_amazing_work_you_have_learned_four_powerful_ideas_we_co_8.mp3",
  "Station one — the Balance Scale! Look at the two objects. Think about which one is heavier. The balance scale will tip toward the heavier side. Let's go!": "assets/audio/audio_station_one_the_balance_scale_look_at_the_two_objects_t_9.mp3",
  "Station two — Mass Reader! Look at the dial on the scale. The needle is pointing to a number. Can you read the mass and pick the right answer? Read carefully!": "assets/audio/audio_station_two_mass_reader_look_at_the_dial_on_the_scale_t_10.mp3",
  "Final station — Unit Converter! You will see a mass in grams or kilograms with one blank. Use what you know about 1 kg equals 1000 g to fill it in. You've got this!": "assets/audio/audio_final_station_unit_converter_you_will_see_a_mass_in_gra_11.mp3",
  "Excellent! You've got it!": "assets/audio/audio_excellent_youve_got_it_12.mp3",
  "Brilliant! Keep going!": "assets/audio/audio_brilliant_keep_going_13.mp3",
  "That's exactly right! Well done!": "assets/audio/audio_thats_exactly_right_well_done_14.mp3",
  "Not quite, but good try! Remember: 1 kilogram equals 1000 grams.": "assets/audio/audio_not_quite_but_good_try_remember_1_kilogram_equals_1000__15.mp3",
  "Almost! Check the units carefully and try again.": "assets/audio/audio_almost_check_the_units_carefully_and_try_again_16.mp3",
  "The Boss Battle begins! Answer five questions correctly to defeat the Scale Boss and claim your Mass Master trophy!": "assets/audio/audio_the_boss_battle_begins_answer_five_questions_correctly__17.mp3",
  "You defeated the Scale Boss! The Golden Weighing Trophy is yours!": "assets/audio/audio_you_defeated_the_scale_boss_the_golden_weighing_trophy__18.mp3",
};
